# Generated by Django 4.1.3 on 2022-12-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user_id',
            new_name='userio_id',
        ),
    ]
